"""auto

Revision ID: 1d19f38237f4
Revises: 
Create Date: 2025-11-15 12:30:46.085221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d19f38237f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('chinese_keywords', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_keywords', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title')
    )
    op.create_index('idx_seo_chinese_title', 'seo', ['chinese_title'], unique=False)
    op.create_index('idx_seo_created_at_desc', 'seo', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_seo_id', 'seo', ['id'], unique=False)
    op.create_index('idx_seo_updated_at_desc', 'seo', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unsubscribed_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tags_created_at_desc', 'tags', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_tags_id', 'tags', ['id'], unique=False)
    op.create_index('idx_tags_slug', 'tags', ['slug'], unique=False)
    op.create_index('idx_tags_updated_at_desc', 'tags', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_name')
    )
    op.create_index('idx_taxes_active_name', 'taxes', ['is_active', 'tax_name'], unique=False)
    op.create_index('idx_taxes_created_at_desc', 'taxes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_taxes_id', 'taxes', ['id'], unique=False)
    op.create_index('idx_taxes_is_active', 'taxes', ['is_active'], unique=False)
    op.create_index('idx_taxes_tax_name', 'taxes', ['tax_name'], unique=False)
    op.create_index('idx_taxes_updated_at_desc', 'taxes', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='roletype'), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_created_at_desc', 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_get_user_by_email', 'users', ['email', 'is_active', 'is_verified', 'is_deleted'], unique=False)
    op.create_index('idx_users_get_user_by_id', 'users', ['id', 'is_active', 'is_verified', 'is_deleted'], unique=False)
    op.create_index('idx_users_get_user_by_username', 'users', ['username', 'is_active', 'is_verified'], unique=False)
    op.create_index('idx_users_id', 'users', ['id'], unique=False)
    op.create_index('idx_users_updated_at_desc', 'users', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('verified', 'reset', name='codetype'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_codes_created_at_desc', 'codes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_codes_expires_at_desc', 'codes', [sa.literal_column('expires_at DESC')], unique=False)
    op.create_index('idx_codes_get_valid_code', 'codes', ['user_id', 'type', 'expires_at', 'is_used'], unique=False)
    op.create_index('idx_codes_is_used', 'codes', ['is_used'], unique=False)
    op.create_index('idx_codes_type', 'codes', ['type'], unique=False)
    op.create_index('idx_codes_user_id', 'codes', ['user_id'], unique=False)
    op.create_index('idx_codes_validate_code', 'codes', ['user_id', 'code', 'type', 'expires_at', 'is_used'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'audio', 'document', 'other', name='mediatype'), nullable=False),
    sa.Column('is_avatar', sa.Boolean(), nullable=False),
    sa.Column('is_content_audio', sa.Boolean(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('original_filepath_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_filepath_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('watermark_filepath_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_media_created_at_desc', 'media', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_media_id', 'media', ['id'], unique=False)
    op.create_index('idx_media_id_uuid_user', 'media', ['id', 'uuid', 'user_id'], unique=False)
    op.create_index('idx_media_is_avatar', 'media', ['is_avatar'], unique=False)
    op.create_index('idx_media_type', 'media', ['type'], unique=False)
    op.create_index('idx_media_user_id', 'media', ['user_id'], unique=False)
    op.create_index('idx_media_uuid', 'media', ['uuid'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('blog', 'project', 'board', 'friend', 'about', name='sectiontype'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['seo_id'], ['seo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_sections_chinese_title', 'sections', ['chinese_title'], unique=False)
    op.create_index('idx_sections_created_at_desc', 'sections', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_sections_id', 'sections', ['id'], unique=False)
    op.create_index('idx_sections_is_active', 'sections', ['is_active'], unique=False)
    op.create_index('idx_sections_parent_active', 'sections', ['parent_id', 'is_active'], unique=False)
    op.create_index('idx_sections_parent_id', 'sections', ['parent_id'], unique=False)
    op.create_index('idx_sections_seo_id', 'sections', ['seo_id'], unique=False)
    op.create_index('idx_sections_slug', 'sections', ['slug'], unique=False)
    op.create_index('idx_sections_type', 'sections', ['type'], unique=False)
    op.create_index('idx_sections_type_active', 'sections', ['type', 'is_active'], unique=False)
    op.create_index('idx_sections_updated_at_desc', 'sections', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'github', name='socialprovider'), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    op.create_index('idx_social_accounts_get_social_account', 'social_accounts', ['user_id', 'provider', 'provider_user_id'], unique=False)
    op.create_index('idx_social_accounts_provider', 'social_accounts', ['provider'], unique=False)
    op.create_index('idx_social_accounts_provider_user_id', 'social_accounts', ['provider_user_id'], unique=False)
    op.create_index('idx_social_accounts_user_id', 'social_accounts', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('type', sa.Enum('access', 'refresh', name='tokentype'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expired_at', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jit')
    )
    op.create_index('idx_tokens_cleanup_tokens_by_active', 'tokens', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_tokens_cleanup_tokens_by_expired', 'tokens', ['user_id', 'expired_at'], unique=False)
    op.create_index('idx_tokens_cleanup_tokens_by_expired_active', 'tokens', ['user_id', 'expired_at', 'is_active'], unique=False)
    op.create_index('idx_tokens_created_at_desc', 'tokens', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_tokens_delete_old_token_by_user_id_type', 'tokens', ['user_id', 'type'], unique=False)
    op.create_index('idx_tokens_expired_at', 'tokens', ['expired_at'], unique=False)
    op.create_index('idx_tokens_expired_at_desc', 'tokens', [sa.literal_column('expired_at DESC')], unique=False)
    op.create_index('idx_tokens_generate_access_token', 'tokens', ['user_id', 'jit', 'type', 'is_active', 'expired_at'], unique=False)
    op.create_index('idx_tokens_get_current_user', 'tokens', ['user_id', 'type', 'is_active', 'expired_at'], unique=False)
    op.create_index('idx_tokens_get_user_tokens', 'tokens', ['user_id', 'expired_at', 'is_active'], unique=False)
    op.create_index('idx_tokens_is_active', 'tokens', ['is_active'], unique=False)
    op.create_index('idx_tokens_jit', 'tokens', ['jit'], unique=False)
    op.create_index('idx_tokens_revoke_user_tokens', 'tokens', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_tokens_type', 'tokens', ['type'], unique=False)
    op.create_index('idx_tokens_user_id', 'tokens', ['user_id'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('seo_id', sa.Integer(), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('chinese_content', sa.JSON(), nullable=False),
    sa.Column('english_content', sa.JSON(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seo_id'], ['seo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_blogs_id', 'blogs', ['id'], unique=False)
    op.create_index('idx_blogs_section_id', 'blogs', ['section_id'], unique=False)
    op.create_index('idx_blogs_seo_id', 'blogs', ['seo_id'], unique=False)
    op.create_index('idx_blogs_slug', 'blogs', ['slug'], unique=False)
    op.create_index('idx_blogs_user_id', 'blogs', ['user_id'], unique=False)
    op.create_index('idx_users_created_at_desc', 'blogs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_updated_at_desc', 'blogs', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title')
    )
    op.create_index('idx_boards_chinese_title', 'boards', ['chinese_title'], unique=False)
    op.create_index('idx_boards_created_at_desc', 'boards', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_boards_id', 'boards', ['id'], unique=False)
    op.create_index('idx_boards_section_id', 'boards', ['section_id'], unique=False)
    op.create_index('idx_boards_updated_at_desc', 'boards', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title')
    )
    op.create_index('idx_friends_chinese_title', 'friends', ['chinese_title'], unique=False)
    op.create_index('idx_friends_created_at_desc', 'friends', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_friends_id', 'friends', ['id'], unique=False)
    op.create_index('idx_friends_section_id', 'friends', ['section_id'], unique=False)
    op.create_index('idx_friends_updated_at_desc', 'friends', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('web', 'mobile', 'desktop', 'other', name='projecttype'), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('seo_id', sa.Integer(), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('chinese_content', sa.JSON(), nullable=False),
    sa.Column('english_content', sa.JSON(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seo_id'], ['seo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chinese_title'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_projects_chinese_title', 'projects', ['chinese_title'], unique=False)
    op.create_index('idx_projects_id', 'projects', ['id'], unique=False)
    op.create_index('idx_projects_is_published', 'projects', ['is_published'], unique=False)
    op.create_index('idx_projects_seo_id', 'projects', ['seo_id'], unique=False)
    op.create_index('idx_projects_type', 'projects', ['type'], unique=False)
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blog_comment_blog_id', 'blog_comment', ['blog_id'], unique=False)
    op.create_index('idx_blog_comment_created_at_desc', 'blog_comment', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_blog_comment_id', 'blog_comment', ['id'], unique=False)
    op.create_index('idx_blog_comment_is_deleted', 'blog_comment', ['is_deleted'], unique=False)
    op.create_index('idx_blog_comment_parent_id', 'blog_comment', ['parent_id'], unique=False)
    op.create_index('idx_blog_comment_updated_at_desc', 'blog_comment', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_blog_comment_user_id', 'blog_comment', ['user_id'], unique=False)
    op.create_table('blog_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_index('idx_blog_stats_blog_id', 'blog_stats', ['blog_id'], unique=False)
    op.create_index('idx_blog_stats_id', 'blog_stats', ['id'], unique=False)
    op.create_table('blog_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_index('idx_blog_status_blog_id', 'blog_status', ['blog_id'], unique=False)
    op.create_index('idx_blog_status_created_at_desc', 'blog_status', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_blog_status_id', 'blog_status', ['id'], unique=False)
    op.create_index('idx_blog_status_is_archived', 'blog_status', ['is_archived'], unique=False)
    op.create_index('idx_blog_status_is_featured', 'blog_status', ['is_featured'], unique=False)
    op.create_index('idx_blog_status_is_published', 'blog_status', ['is_published'], unique=False)
    op.create_index('idx_blog_status_updated_at_desc', 'blog_status', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_blog_status_user_id', 'blog_status', ['user_id'], unique=False)
    op.create_table('blog_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('chinese_summary', sa.JSON(), nullable=False),
    sa.Column('english_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_index('idx_blog_summary_blog_id', 'blog_summary', ['blog_id'], unique=False)
    op.create_index('idx_blog_summary_created_at_desc', 'blog_summary', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_blog_summary_id', 'blog_summary', ['id'], unique=False)
    op.create_index('idx_blog_summary_updated_at_desc', 'blog_summary', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('blog_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blog_tag_blog_id', 'blog_tag', ['blog_id'], unique=False)
    op.create_index('idx_blog_tag_blog_id_tag_id', 'blog_tag', ['blog_id', 'tag_id'], unique=False)
    op.create_index('idx_blog_tag_created_at_desc', 'blog_tag', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_blog_tag_id', 'blog_tag', ['id'], unique=False)
    op.create_index('idx_blog_tag_tag_id', 'blog_tag', ['tag_id'], unique=False)
    op.create_index('idx_blog_tag_updated_at_desc', 'blog_tag', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('blog_tts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('chinese_tts_id', sa.Integer(), nullable=True),
    sa.Column('english_tts_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chinese_tts_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['english_tts_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blog_tts_blog_id', 'blog_tts', ['blog_id'], unique=False)
    op.create_index('idx_blog_tts_blog_id_chinese_tts_id', 'blog_tts', ['blog_id', 'chinese_tts_id'], unique=False)
    op.create_index('idx_blog_tts_blog_id_chinese_tts_id_english_tts_id', 'blog_tts', ['blog_id', 'chinese_tts_id', 'english_tts_id'], unique=False)
    op.create_index('idx_blog_tts_blog_id_english_tts_id', 'blog_tts', ['blog_id', 'english_tts_id'], unique=False)
    op.create_index('idx_blog_tts_chinese_tts_id', 'blog_tts', ['chinese_tts_id'], unique=False)
    op.create_index('idx_blog_tts_created_at_desc', 'blog_tts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_blog_tts_english_tts_id', 'blog_tts', ['english_tts_id'], unique=False)
    op.create_index('idx_blog_tts_id', 'blog_tts', ['id'], unique=False)
    op.create_index('idx_blog_tts_updated_at_desc', 'blog_tts', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('board_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['board_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_board_comments_board_created', 'board_comments', ['board_id', 'created_at'], unique=False)
    op.create_index('idx_board_comments_board_id', 'board_comments', ['board_id'], unique=False)
    op.create_index('idx_board_comments_board_id_user_id', 'board_comments', ['board_id', 'user_id'], unique=False)
    op.create_index('idx_board_comments_created_at_desc', 'board_comments', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_board_comments_id', 'board_comments', ['id'], unique=False)
    op.create_index('idx_board_comments_is_deleted', 'board_comments', ['is_deleted'], unique=False)
    op.create_index('idx_board_comments_parent_id', 'board_comments', ['parent_id'], unique=False)
    op.create_index('idx_board_comments_updated_at_desc', 'board_comments', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_board_comments_user_id', 'board_comments', ['user_id'], unique=False)
    op.create_table('friend_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('featured', 'normal', 'hidden', name='friendtype'), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('site_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('chinese_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('english_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chinese_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('english_description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_friend_lists_created_at_desc', 'friend_lists', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_friend_lists_friend_id', 'friend_lists', ['friend_id'], unique=False)
    op.create_index('idx_friend_lists_id', 'friend_lists', ['id'], unique=False)
    op.create_index('idx_friend_lists_type', 'friend_lists', ['type'], unique=False)
    op.create_index('idx_friend_lists_updated_at_desc', 'friend_lists', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_friend_lists_user_id', 'friend_lists', ['user_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tax_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('payment_type', sa.Enum('card', 'link', 'klarna', 'afterpay_clearpay', 'alipay', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('cancel', 'success', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('idx_payment_record_created_at_desc', 'payment_records', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_payment_record_id', 'payment_records', ['id'], unique=False)
    op.create_index('idx_payment_record_order_number', 'payment_records', ['order_number'], unique=False)
    op.create_index('idx_payment_record_payment_status', 'payment_records', ['payment_status'], unique=False)
    op.create_index('idx_payment_record_payment_type', 'payment_records', ['payment_type'], unique=False)
    op.create_index('idx_payment_record_project_id', 'payment_records', ['project_id'], unique=False)
    op.create_index('idx_payment_record_tax_name', 'payment_records', ['tax_name'], unique=False)
    op.create_index('idx_payment_record_user_id', 'payment_records', ['user_id'], unique=False)
    op.create_table('project_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_monetizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saved_blog_blog_id', 'saved_blog', ['blog_id'], unique=False)
    op.create_index('idx_saved_blog_created_at_desc', 'saved_blog', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_saved_blog_id', 'saved_blog', ['id'], unique=False)
    op.create_index('idx_saved_blog_updated_at_desc', 'saved_blog', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_saved_blog_user_id', 'saved_blog', ['user_id'], unique=False)
    op.create_index('idx_saved_blog_user_id_blog_id', 'saved_blog', ['user_id', 'blog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saved_blog_user_id_blog_id', table_name='saved_blog')
    op.drop_index('idx_saved_blog_user_id', table_name='saved_blog')
    op.drop_index('idx_saved_blog_updated_at_desc', table_name='saved_blog')
    op.drop_index('idx_saved_blog_id', table_name='saved_blog')
    op.drop_index('idx_saved_blog_created_at_desc', table_name='saved_blog')
    op.drop_index('idx_saved_blog_blog_id', table_name='saved_blog')
    op.drop_table('saved_blog')
    op.drop_table('project_monetizations')
    op.drop_table('project_attachments')
    op.drop_index('idx_payment_record_user_id', table_name='payment_records')
    op.drop_index('idx_payment_record_tax_name', table_name='payment_records')
    op.drop_index('idx_payment_record_project_id', table_name='payment_records')
    op.drop_index('idx_payment_record_payment_type', table_name='payment_records')
    op.drop_index('idx_payment_record_payment_status', table_name='payment_records')
    op.drop_index('idx_payment_record_order_number', table_name='payment_records')
    op.drop_index('idx_payment_record_id', table_name='payment_records')
    op.drop_index('idx_payment_record_created_at_desc', table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index('idx_friend_lists_user_id', table_name='friend_lists')
    op.drop_index('idx_friend_lists_updated_at_desc', table_name='friend_lists')
    op.drop_index('idx_friend_lists_type', table_name='friend_lists')
    op.drop_index('idx_friend_lists_id', table_name='friend_lists')
    op.drop_index('idx_friend_lists_friend_id', table_name='friend_lists')
    op.drop_index('idx_friend_lists_created_at_desc', table_name='friend_lists')
    op.drop_table('friend_lists')
    op.drop_index('idx_board_comments_user_id', table_name='board_comments')
    op.drop_index('idx_board_comments_updated_at_desc', table_name='board_comments')
    op.drop_index('idx_board_comments_parent_id', table_name='board_comments')
    op.drop_index('idx_board_comments_is_deleted', table_name='board_comments')
    op.drop_index('idx_board_comments_id', table_name='board_comments')
    op.drop_index('idx_board_comments_created_at_desc', table_name='board_comments')
    op.drop_index('idx_board_comments_board_id_user_id', table_name='board_comments')
    op.drop_index('idx_board_comments_board_id', table_name='board_comments')
    op.drop_index('idx_board_comments_board_created', table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_index('idx_blog_tts_updated_at_desc', table_name='blog_tts')
    op.drop_index('idx_blog_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_english_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_created_at_desc', table_name='blog_tts')
    op.drop_index('idx_blog_tts_chinese_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_blog_id_english_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_blog_id_chinese_tts_id_english_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_blog_id_chinese_tts_id', table_name='blog_tts')
    op.drop_index('idx_blog_tts_blog_id', table_name='blog_tts')
    op.drop_table('blog_tts')
    op.drop_index('idx_blog_tag_updated_at_desc', table_name='blog_tag')
    op.drop_index('idx_blog_tag_tag_id', table_name='blog_tag')
    op.drop_index('idx_blog_tag_id', table_name='blog_tag')
    op.drop_index('idx_blog_tag_created_at_desc', table_name='blog_tag')
    op.drop_index('idx_blog_tag_blog_id_tag_id', table_name='blog_tag')
    op.drop_index('idx_blog_tag_blog_id', table_name='blog_tag')
    op.drop_table('blog_tag')
    op.drop_index('idx_blog_summary_updated_at_desc', table_name='blog_summary')
    op.drop_index('idx_blog_summary_id', table_name='blog_summary')
    op.drop_index('idx_blog_summary_created_at_desc', table_name='blog_summary')
    op.drop_index('idx_blog_summary_blog_id', table_name='blog_summary')
    op.drop_table('blog_summary')
    op.drop_index('idx_blog_status_user_id', table_name='blog_status')
    op.drop_index('idx_blog_status_updated_at_desc', table_name='blog_status')
    op.drop_index('idx_blog_status_is_published', table_name='blog_status')
    op.drop_index('idx_blog_status_is_featured', table_name='blog_status')
    op.drop_index('idx_blog_status_is_archived', table_name='blog_status')
    op.drop_index('idx_blog_status_id', table_name='blog_status')
    op.drop_index('idx_blog_status_created_at_desc', table_name='blog_status')
    op.drop_index('idx_blog_status_blog_id', table_name='blog_status')
    op.drop_table('blog_status')
    op.drop_index('idx_blog_stats_id', table_name='blog_stats')
    op.drop_index('idx_blog_stats_blog_id', table_name='blog_stats')
    op.drop_table('blog_stats')
    op.drop_index('idx_blog_comment_user_id', table_name='blog_comment')
    op.drop_index('idx_blog_comment_updated_at_desc', table_name='blog_comment')
    op.drop_index('idx_blog_comment_parent_id', table_name='blog_comment')
    op.drop_index('idx_blog_comment_is_deleted', table_name='blog_comment')
    op.drop_index('idx_blog_comment_id', table_name='blog_comment')
    op.drop_index('idx_blog_comment_created_at_desc', table_name='blog_comment')
    op.drop_index('idx_blog_comment_blog_id', table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index('idx_projects_type', table_name='projects')
    op.drop_index('idx_projects_seo_id', table_name='projects')
    op.drop_index('idx_projects_is_published', table_name='projects')
    op.drop_index('idx_projects_id', table_name='projects')
    op.drop_index('idx_projects_chinese_title', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_friends_updated_at_desc', table_name='friends')
    op.drop_index('idx_friends_section_id', table_name='friends')
    op.drop_index('idx_friends_id', table_name='friends')
    op.drop_index('idx_friends_created_at_desc', table_name='friends')
    op.drop_index('idx_friends_chinese_title', table_name='friends')
    op.drop_table('friends')
    op.drop_index('idx_boards_updated_at_desc', table_name='boards')
    op.drop_index('idx_boards_section_id', table_name='boards')
    op.drop_index('idx_boards_id', table_name='boards')
    op.drop_index('idx_boards_created_at_desc', table_name='boards')
    op.drop_index('idx_boards_chinese_title', table_name='boards')
    op.drop_table('boards')
    op.drop_index('idx_users_updated_at_desc', table_name='blogs')
    op.drop_index('idx_users_created_at_desc', table_name='blogs')
    op.drop_index('idx_blogs_user_id', table_name='blogs')
    op.drop_index('idx_blogs_slug', table_name='blogs')
    op.drop_index('idx_blogs_seo_id', table_name='blogs')
    op.drop_index('idx_blogs_section_id', table_name='blogs')
    op.drop_index('idx_blogs_id', table_name='blogs')
    op.drop_table('blogs')
    op.drop_index('idx_tokens_user_id', table_name='tokens')
    op.drop_index('idx_tokens_type', table_name='tokens')
    op.drop_index('idx_tokens_revoke_user_tokens', table_name='tokens')
    op.drop_index('idx_tokens_jit', table_name='tokens')
    op.drop_index('idx_tokens_is_active', table_name='tokens')
    op.drop_index('idx_tokens_get_user_tokens', table_name='tokens')
    op.drop_index('idx_tokens_get_current_user', table_name='tokens')
    op.drop_index('idx_tokens_generate_access_token', table_name='tokens')
    op.drop_index('idx_tokens_expired_at_desc', table_name='tokens')
    op.drop_index('idx_tokens_expired_at', table_name='tokens')
    op.drop_index('idx_tokens_delete_old_token_by_user_id_type', table_name='tokens')
    op.drop_index('idx_tokens_created_at_desc', table_name='tokens')
    op.drop_index('idx_tokens_cleanup_tokens_by_expired_active', table_name='tokens')
    op.drop_index('idx_tokens_cleanup_tokens_by_expired', table_name='tokens')
    op.drop_index('idx_tokens_cleanup_tokens_by_active', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('idx_social_accounts_user_id', table_name='social_accounts')
    op.drop_index('idx_social_accounts_provider_user_id', table_name='social_accounts')
    op.drop_index('idx_social_accounts_provider', table_name='social_accounts')
    op.drop_index('idx_social_accounts_get_social_account', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index('idx_sections_updated_at_desc', table_name='sections')
    op.drop_index('idx_sections_type_active', table_name='sections')
    op.drop_index('idx_sections_type', table_name='sections')
    op.drop_index('idx_sections_slug', table_name='sections')
    op.drop_index('idx_sections_seo_id', table_name='sections')
    op.drop_index('idx_sections_parent_id', table_name='sections')
    op.drop_index('idx_sections_parent_active', table_name='sections')
    op.drop_index('idx_sections_is_active', table_name='sections')
    op.drop_index('idx_sections_id', table_name='sections')
    op.drop_index('idx_sections_created_at_desc', table_name='sections')
    op.drop_index('idx_sections_chinese_title', table_name='sections')
    op.drop_table('sections')
    op.drop_index('idx_media_uuid', table_name='media')
    op.drop_index('idx_media_user_id', table_name='media')
    op.drop_index('idx_media_type', table_name='media')
    op.drop_index('idx_media_is_avatar', table_name='media')
    op.drop_index('idx_media_id_uuid_user', table_name='media')
    op.drop_index('idx_media_id', table_name='media')
    op.drop_index('idx_media_created_at_desc', table_name='media')
    op.drop_table('media')
    op.drop_index('idx_codes_validate_code', table_name='codes')
    op.drop_index('idx_codes_user_id', table_name='codes')
    op.drop_index('idx_codes_type', table_name='codes')
    op.drop_index('idx_codes_is_used', table_name='codes')
    op.drop_index('idx_codes_get_valid_code', table_name='codes')
    op.drop_index('idx_codes_expires_at_desc', table_name='codes')
    op.drop_index('idx_codes_created_at_desc', table_name='codes')
    op.drop_table('codes')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_updated_at_desc', table_name='users')
    op.drop_index('idx_users_id', table_name='users')
    op.drop_index('idx_users_get_user_by_username', table_name='users')
    op.drop_index('idx_users_get_user_by_id', table_name='users')
    op.drop_index('idx_users_get_user_by_email', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at_desc', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_taxes_updated_at_desc', table_name='taxes')
    op.drop_index('idx_taxes_tax_name', table_name='taxes')
    op.drop_index('idx_taxes_is_active', table_name='taxes')
    op.drop_index('idx_taxes_id', table_name='taxes')
    op.drop_index('idx_taxes_created_at_desc', table_name='taxes')
    op.drop_index('idx_taxes_active_name', table_name='taxes')
    op.drop_table('taxes')
    op.drop_index('idx_tags_updated_at_desc', table_name='tags')
    op.drop_index('idx_tags_slug', table_name='tags')
    op.drop_index('idx_tags_id', table_name='tags')
    op.drop_index('idx_tags_created_at_desc', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    op.drop_index('idx_seo_updated_at_desc', table_name='seo')
    op.drop_index('idx_seo_id', table_name='seo')
    op.drop_index('idx_seo_created_at_desc', table_name='seo')
    op.drop_index('idx_seo_chinese_title', table_name='seo')
    op.drop_table('seo')
    # ### end Alembic commands ###
